# application: ezgantt
# version: 1
runtime: python38

handlers:
  - url: /main.py
    script: auto

  - url: /
    static_files: website/index.html
    upload: website/index\.html
    secure: always

  - url: /(.*\.html)
    mime_type: text/html
    static_files: website/\1
    upload: website/(.*\.html)
    secure: always

  - url: /js
    static_dir: website/js
    secure: always


